image: python:3.11

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - pip install python-multipart
    - uvicorn app:api --host 0.0.0.0 --port 8080
  artifacts:
    paths:
      - public
  only:
    - main
