version: '3'

services:
  ssh:
    build:
      context: .
      dockerfile: Dockerfile-ssh
    container_name: ssh
    ports:
      - "2222:22"
    volumes:
      - ./authorized_keys:/root/.ssh/authorized_keys
    command: /usr/sbin/sshd -D

  login:
    build:
      context: .
      dockerfile: Dockerfile-login
    container_name: login
    ports:
      - "8080"
